### ISSUE TITLE
Signing out Randomly

### ISSUE THREAD

**Issue by LoneStalkerz** [MHSanaei/3x-ui#2456]
hi there , after new updates, i think it was after version 2.3.10 not sure , but after that panel signs out over and over again randomly , even i tried to save my login info on different browsers and devices but the issue is still there, so please if this problem defines as a bug , i really appreciate that if you fix it. 

Best regards

**Comment by MHSanaei** [comment]
The session was fixed in the latest version.

**Comment by LoneStalkerz** [comment]
Thanks for response, but i even tried the last version , 2.3.12 but the issue is still there, i have 8 panels and this issue occurs for all of them

**Comment by MHSanaei** [comment]
On the last version if you don't set anything for session on setting it will logout after an hour
