### ISSUE TITLE
White screen after update, control panel

### ISSUE THREAD

**Issue by Fonzi1** [MHSanaei/3x-ui#2910]
After performing the update, the panel does not open, just a white screen. Tell me, please, what could be the problem?

**Comment by Fonzi1** [comment]
The issue has been resolved

**Comment by berbunda** [comment]
I have white screen on web panel
I reinstall OS on VPS
I install 3X-UI on new OS
I clean all cookies in my browser
Install certificate in 3X-UI
I still see only white screen and error in systemctl
 TLS handshake error from [my IP]: remote error: tls: bad certificate
